export const USER_LIST = "USER_LIST";
export const POST_LIST = "POST_LIST";
export const CURRENT_POSTS_USER = 'CURRENT_POSTS_USER';
export const CURRENT_ID_USER = "CURRENT_ID_USER"
export const COMMENTS_LIST = "COMMENTS_LIST";
export const MODAL_WINDOW_ACTIVE = "MODAL_WINDOW_ACTIVE";
export const FORM_POST_TRUE = "FORM_POST_TRUE";
